### ISSUE TITLE
发现一个页面方法调用两次

### ISSUE THREAD

**Issue by tanteng** [mojifan/MoBlog#1]
我发现博客运行的时候，比如首页，我在/common/models/Content.php的find()方法，打印一个东西出来，你看刷新页面的时候，会发现打印两次，其他地方也是这样，刷新一次页面调用两次方法。是因为其他地方也调用了find吗。

我还觉得页面响应速度好慢。

**Comment by mojifan** [comment]
打印两次 是因为他有子类  Content是个抽象类，不建议直接用 而是用他的之类Post Page Attachment

**Comment by tanteng** [comment]
return new ContentQuery(get_called_class(),['contentType'=>static::TYPE]);

我不是很明白这句话，get_called_class的值是models/post，后面是contentType也是post，但是在ContentQuery类里面没看到接收这两个参数的地方啊，找了父类没有，我是初学Yii，请赐教，谢谢！

**Comment by mojifan** [comment]
http://apidoc.yii2.cn/guide-db-active-record.html  看最下面那个作用域， 至于没找到接收参数的地方，应该看她的父类ActiveQuery类
