### ISSUE TITLE
关于前后台WEB目录的问题

### ISSUE THREAD

**Issue by tanteng** [mojifan/MoBlog#2]
hi，问你个问题

Yii官方advance例子，前后台独立开共用Yii核心，分别建立了Fronted和bacend文件夹，两个文件夹里面都有一个WEB文件夹，感觉完全独立分开。

而你这个博客前后台也是两个文件夹，独立开来，但是WEB目录是放在外面，共用一个WEB目录，一般做法都是这样的吗？

**Comment by mojifan** [comment]
这个看情况吧，我只是为了部署方便放在一起 ，也可以分开 分别绑定不同的域名

**Comment by tanteng** [comment]
也可以不绑定二级域名，后台就www.xx.com/backend/这样访问

**Comment by mojifan** [comment]
也可以，在web目录下 建个backend文件夹，把backend的入口index.php文件放到这里就可以，当然，index.php里的引用文件路径要自己修改一下
