### ISSUE TITLE
demo里面的登录密码不是123456

### ISSUE THREAD

**Issue by zengdp** [mojifan/MoBlog#4]

**Comment by mojifan** [comment]
sorry 我也忘了密码多少了 你本地搭建吧

**Comment by zengdp** [comment]
配置的时候，common/config/main-local.php中的数据库配置，host应该配置为localhost，而不是192.168.10.10，你可能忘了改了。

**Comment by zengdp** [comment]
本地搭建成功，很漂亮啊，我要去研究源码了
